### ISSUE TITLE
Armature not affecting model

### ISSUE THREAD

**Issue by perfeksthun** [EdyJ/blender-to-unity-fbx-exporter#12] opened 2020-09-15 16:42 UTC
When I use this importer, my model is no longer being influenced by the armature in Unity. When I try to play the animations in the model import settings, nothing happens. This is not the case when I export as .fbx the normal way, or when I save as .blend. I've tried toggling some of the options in the export window but nothing has fixed this. Am I missing something or is this not currently working?

EDIT: I should add that the armature is still animating it just isn't affecting the model.

**Comment by EdyJ** [comment] 2020-09-15 17:03
This is a duplicate of #10, which has been fixed in the latest version.

**Closed by EdyJ** 2020-09-15 17:03 UTC
Labels: duplicate
