### ISSUE TITLE
Animation not working in unity when using this add on

### ISSUE THREAD

**Issue by yusufalibrahim1994** [EdyJ/blender-to-unity-fbx-exporter#13] opened 2020-10-06 10:03 UTC
The animation works when using the built in fbx exporter in blender but not with the unity fbx exporter. Are there specific settings I should change in blender or Unity to fix this issue?

**Comment by EdyJ** [comment] 2020-10-06 11:54
This seems like a duplicate of #10, which is already fixed in the most recent version. If you still experience the problem with the latest version of the Unity FBX Exporter, then feel free to reopen this issue and include a simple .blend file that reproduces the problem.

**Closed by EdyJ** 2020-10-06 11:54 UTC
